### ISSUE TITLE
[1.15.2]Item Clear does not work

### ISSUE THREAD

**Issue by EnterFor** [Darkere/CrashUtilities#1]
`
["Item Clear"]
	#Waiting time between Checks in Minutes
	#Range: 0 ~ 1440
	timer = 4
	#Text to display in TitleCommand
	titletext = "物品清理"
	#Chat warning, Comma separated, in seconds
	warnings = "5,20"
	#Do a clear if there are more than X items
	#Range: > 0
	maximum = 500
	#Text to Display in Chat when Item. First % will be replaced by Value. In red, encased in [=== 
	warningtext = "% 秒后清理地面物品"
	#Run a Title command on first warning
	title = true
	#Enable regular ItemClear
	enabled = false

["Memory Checker"]
	#Time between Memory Checks that will get saved for display(in seconds)
	#Range: > 0
	timer = 300
	#Threshold at which the Memory checker will diplay a warning in the Log (in MB)
	#Range: > 0
	threshold = 500
	#Enable the Memory checker
	enabled = true

`
This is my configuration file. I've been waiting for a long time without any prompt from the server
Forge：31.1.35

**Comment by EnterFor** [comment]
I'm Chinese, so I customized the prompt

**Comment by Darkere** [comment]
#Enable regular ItemClear
enabled = false

This needs to be set to true to enable the function.

**Comment by EnterFor** [comment]
When I changed true, there was still no information in the game

**Comment by Darkere** [comment]
The clear  will also only run if there are more than 500 items on the ground. That's Item Entities up to 64 items can be in an item entity

**Comment by EnterFor** [comment]
I see. I finally understand.
I thought it was regularly cleaned.
Thanks
