### ISSUE TITLE
Item Clear and Memory Checker not work

### ISSUE THREAD

**Issue by frank89722** [Darkere/CrashUtilities#12]
I'm using CrashUtilities-3.8.1
Forge version is 36.0.15

This is my config file: https://gist.github.com/frank89722/7195ab8caa8258960a45440e8c4e7c76

This is what my test world looks like:
![image](https://user-images.githubusercontent.com/10683361/108584962-4f659e80-7380-11eb-9721-4cedeeafc147.png)
![image](https://user-images.githubusercontent.com/10683361/108584970-58567000-7380-11eb-9d92-5025ea8903db.png)

The Item clear task never starts even I use 'crashutilities callItemClear' command. There is no chat output and log.

Memory Checker seems like having the same issue.

**Comment by sprocketaudio** [comment]
Same problem here.. have to use GUI to do manually.. hoping for fix soon!

crashutilities-3.8.1.jar

**Comment by frank89722** [comment]
Seems like the item clear still not work in cu-3.9.2
When I try to force it to start with /cu callItemClear I got an error message in the chat and no error showing up in the log.
![image](https://user-images.githubusercontent.com/10683361/114573457-f98be380-9caa-11eb-801d-1eda50379533.png)

This is new config file: https://gist.github.com/frank89722/7195ab8caa8258960a45440e8c4e7c76
