### ISSUE TITLE
1.16.5 MC Relogging Issues

### ISSUE THREAD

**Issue by litjohn50** [Darkere/CrashUtilities#15]
You can join a server no problem if you relaunch a modpack. But if you happen to relog, with the mod in your client it will throw null point errors and make you have to relaunch to rejoin. 

After removing the mod from the client me and a few other people no longer had issues connecting to a server.

Connecting Log to a server
https://gist.github.com/litjohn50/257b40a792bc383c2c06c295d1deeb03

**Comment by ProsperCraft** [comment]
Subscribed, I can confirm this issue.

**Comment by WindFox** [comment]
Also seeing this in my modpack.

**Comment by Darkere** [comment]
fixed in  3.10.0
