### ISSUE TITLE
[1.15.2] Mod does not allow server to fully stop.

### ISSUE THREAD

**Issue by WindFox** [Darkere/CrashUtilities#2]
I added this mod to my server to help out with things and discovered that it will not let the server process to end. If it server crashes, it just sits in a zombie state. If I give it the stop command, it saves and stops what it can, but the server process still continues to run in a zombie state as well.

Either way, I have to kill the server process to allow the server to restart.

I have tested this on a server with just this mod and nothing else and it still acts up.

**Comment by Darkere** [comment]
Oh, I have a suspicion on why that might be. Thank you for the report.

**Comment by Darkere** [comment]
This should be fixed in the latest update can you check?

**Comment by WindFox** [comment]
Sorry, but that'd be a nope on that.
I give the server the stop command and it does all the saving it needs then just sits there until I force kill it.

**Comment by Darkere** [comment]
Did you get an error this time around? Just tested it myself and encountered one. 

Hope it's the same.

**Comment by WindFox** [comment]
No. There is no error. Just..... nothing.

**Comment by Darkere** [comment]
Ok then please tell me what you are using/how you are running the test. After fixing the issue that produced an error I'm not having any problems.

**Comment by WindFox** [comment]
Well. It's pretty simple.

I just startup the server. then give it the STOP command when it's fully started.

First I used a backup of my public server. And it happened when I told the server to STOP.
Then I took out the mods and world folder, made new ones. Mods folder only contained this mod with nothing else. Again. It just sat there after I gave it the STOP command.

Then I made a new server folder with just this mod and an updated forge (31.1.77 since my pack is on 31.1.41) thinking that maybe it's just forge. Nope.

I am using Java 8. Latest Oracle version on my computer, (I think, latest) OpenJDK on my public server.

**Comment by WindFox** [comment]
Well, this is interesting. Using the updated Forge test, I deleted the world folder and tried again. Also making sure to give you logs and screenshots, when I start getting an error when I give the STOP command.
https://pastebin.com/uhyHxpgx

**Comment by Darkere** [comment]
paste is private?

**Comment by WindFox** [comment]
Sorry about that. Forgot to change that setting.

Also, went back to the older Forge and same error.
I wonder if my older world file had something in it to suppress that error.
Server still doesn't fully stop, though.

**Comment by Darkere** [comment]
Ah that error is the same one I got. Can you try with this version? 
[crashutilities-2.4.zip](https://github.com/Darkere/CrashUtilities/files/4606165/crashutilities-2.4.zip)
(need to unzip the file ofc)

**Comment by WindFox** [comment]
Good news: That error's gone.
Bad news: My issue is still here.

Here are some screenshots:
![Clipboard-20200510-01](https://user-images.githubusercontent.com/3812388/81505578-45295680-92be-11ea-8d91-8a72d5062b6a.png)
This is with mod. After I give the STOP command.

Task manager still shows Java running:
![Clipboard-20200510-02](https://user-images.githubusercontent.com/3812388/81505596-6d18ba00-92be-11ea-8ad0-b4ec9e5b1f87.png)


This is what I expected to happen after telling the server to stop:
![Clipboard-20200510-03](https://user-images.githubusercontent.com/3812388/81505601-7efa5d00-92be-11ea-8d2d-ff70185f5f9a.png)

Task manager shows no Java:
![Clipboard-20200510-04](https://user-images.githubusercontent.com/3812388/81505643-cf71ba80-92be-11ea-8913-a874229898e3.png)

**Comment by Darkere** [comment]
This is with just CU installed right?

Can you share the script you are using to launch the server?

Also, the serverconfig in case you've changed anything there.

**Comment by WindFox** [comment]
Just CU.
![Clipboard-20200510](https://user-images.githubusercontent.com/3812388/81507031-6727d680-92c8-11ea-921a-91ab1144512f.png)

My ServerStart.bat: https://pastebin.com/ZyLfUqxY
(The other server just has the Forge version changed)

My server.properties: https://pastebin.com/cqLVSQUL
(The other server is just the default one that gets generated with a new server.)

**Comment by Darkere** [comment]
Ah I meant the config of the mod. It can be found under world/serverconfig/

**Comment by WindFox** [comment]
Ah. Right. The NEW OTHER config folder.

Here you go: https://pastebin.com/XJVTn957

I haven't touched that file. Only just recently learned about that folder to fix an issue with another mod that was crashing my server.

**Comment by Darkere** [comment]
Alrighty. Launching directly from the jar file doesn't cause the window to stay, which confused me more than it should have. (it produced a hidden ghost process instead -.-).

I'm fairly certain I fixed it now. But please test one last time 
[crashutilities-2.4.zip](https://github.com/Darkere/CrashUtilities/files/4606623/crashutilities-2.4.zip)

**Comment by WindFox** [comment]
As a fellow programmer, I chuckled at this.

But yeah. You got it. All fixed!

**Comment by Darkere** [comment]
nice
