### ISSUE TITLE
Issue/bug with force unloading chunks with players that are actively playing

### ISSUE THREAD

**Issue by bigbluu722** [Darkere/CrashUtilities#23]
Currently today I've found an issue with this mod force unloading my personal chunks on my server even when I've been actively playing for the past week or so. The issue seems to even persist even while I'm online. 

Here are some server logs for reference (they should have timestamps to show the time/date):
[https://gist.github.com/ea4ab08a5a31c0623d303969fda92c86](https://gist.github.com/ea4ab08a5a31c0623d303969fda92c86)

**Comment by Darkere** [comment]
This is a config option that is not enabled by default...

**Comment by bigbluu722** [comment]
It is currently enabled by default on All the Mods 6 modpack, but are you gonna tell me that you won't look into the issue just because the feature isn't enabled by default on the base version of the mod?

**Comment by Darkere** [comment]
Oh I misread. 

The function works by looking up your playerdata file and looks up when that has been last modified to determine which chunks to unload. Any idea if someone might have restored that from a backup or something?

I don't really see a way for it to just not notice you being online. Unless the file was write protected or something and not changed while you were playing.

**Comment by bigbluu722** [comment]
I believe I've seemed to of found the issue. When one of my admins initially setup the server, he left it in offline mode (as our template server.properties file has it set to offline mode by default to properly use our proxy) but we later changed to online mode after myself and one other user had logged in with offline UUID's. I will try to remove my offline UUID and keep you posted on the issue.

**Comment by bigbluu722** [comment]
This seems to of done the trick, I've waited for a bit to make sure and it hasn't shown back up in console logs, nor has it unloaded my chunks.
