### ISSUE TITLE
[1.15.2]2.5 Unable to enter server

### ISSUE THREAD

**Issue by mcfensi** [Darkere/CrashUtilities#3]
Failed to synchronize registry data from server, closing connection

**Comment by Darkere** [comment]
Can you post your debug.log?

**Comment by Darkere** [comment]
Nvm. I see the issue. Gonna work on a fix.

**Comment by mcfensi** [comment]
[debug.log](https://github.com/Darkere/CrashUtilities/files/4827789/debug.log)
[debug.log](https://github.com/Darkere/CrashUtilities/files/4827794/debug.log)

**Comment by Darkere** [comment]
This unfortunately requires some rewriting on my part. Expect a fix within the next few days.

You can either use an older version or install the mod on both client and server for now.

**Comment by Darkere** [comment]
Fixed in version 2.6
