### ISSUE TITLE
New crash client side due to CU

### ISSUE THREAD

**Issue by Zelioth** [Darkere/CrashUtilities#30]
Howdy, 
I reported an issue with the player tab last time and I'm not sure i've seen an update fixing it yet. maybe has been and I just didn't realize I updated it but have a new one today. 

Hit Control U and it just crashed me right out of my client 
[crash-2022-10-11_19.30.35-client.txt](https://github.com/Darkere/CrashUtilities/files/9760495/crash-2022-10-11_19.30.35-client.txt)

Minecraft 1.19.2
Forge 43.1.34
CU: 6.0

**Comment by Darkere** [comment]
fixed in 6.1
