### ISSUE TITLE
Ability to remove entity type player

### ISSUE THREAD

**Issue by firemaster1294** [Darkere/CrashUtilities#31]
Title says it all. When I go in to the entity list with CNTL + U, it gives me the option to delete every entity categorized as a player.

Now, this doesn't result in people being kicked if you do it, but the game starts to behave...weird. Entities stop rendering in. Chunks don't load. Things don't interact with you properly. Notably I found opening doors would result in the top half opening but not the bottom. Interestingly I was still able to open new village chests and have them generate loot.

I might recommend you don't let people remove player entities from the game to prevent this :)

**Comment by Darkere** [comment]
Occasionally this can be a solution for bugged players. So I'm gonna leave it in for now.
