### ISSUE TITLE
Item Clear not working (1.19.2)

### ISSUE THREAD

**Issue by sprocketaudio** [Darkere/CrashUtilities#33]
Its tries to run at the threshhold (mines set to 800) but then doesnt clear anything as it says only 3 on ground..

![image](https://user-images.githubusercontent.com/13222732/204095971-9ba96610-e81b-4bab-b534-5b60d850956c.png)

**Comment by sprocketaudio** [comment]
Hi is there any new on this please?

**Comment by Darkere** [comment]
haven't found the time to investigate yet.

**Comment by Darkere** [comment]
fixed in 6.2
