### ISSUE TITLE
[1.20.1] Crash when loading client.

### ISSUE THREAD

**Issue by Gbergz** [Darkere/CrashUtilities#35]
## Title^

**MC:** 1.20.1
**Forge:** 47.0.19
**Crash Utilities:** 8.0.0 | https://legacy.curseforge.com/minecraft/mc-mods/crash-utilities/files/4620856

**Logs:** https://gist.githubusercontent.com/Gbergz/9fc065763e4398f8257c34425a512a69/raw/48f6a78823fa58876c0be48435c2892e0c7a13e6/gistfile1.txt

**Crash-Report**: https://gist.githubusercontent.com/Gbergz/a6afd172962d3ffb2dede0bb66a4e5ef/raw/2804ea5b8d707cff7e7b6d809d6543be247b218b/gistfile1.txt

**Screenshots:**
![screenshot](https://github.com/Darkere/CrashUtilities/assets/26634554/7e0e2972-8fcb-402a-930e-bfe9b3fbf5af)

**Notes:**
No additional mods added, only Forge(47.0.19) & Crash Utilities installed.

**-** Gbergz

**Comment by Darkere** [comment]
Appears to be some sort of forge issue.. Not sure what exactly, but I've worked around it. 8.0.1 is going up. 

Also thanks for reporting... I'll test in production next time <.<

**Comment by Gbergz** [comment]
No problems, thanks for the swift fix! :)

**Comment by Gbergz** [comment]
So, I tested it, still crashed.
https://gist.github.com/Gbergz/c37b46551b33ea0cc3188ef7d2a483d8

**Comment by Darkere** [comment]
This time I made sure that I also tested the version that got uploaded by automation. Fixed in 8.0.2

**Comment by Gbergz** [comment]
Works now!
