### ISSUE TITLE
Command says Incorrect Argument

### ISSUE THREAD

**Issue by Ki-Tan2934** [Darkere/CrashUtilities#36]
It seems most the commands don't work as intended on 1.20.1 build

Running a command `/cu be find minecraft:furnace minecraft:overworld`
outputs Incorrect argument for command

looking into it a bit more you can't specify the item you want to look for

When using BE and you just do /cu be list minecraft:furnace You will get a list of all BE and hover over will display TE command
That command also says it wants the input of a dim but accepts the input of a BE

It's not possible to search for any BE from refined storage

**Comment by Darkere** [comment]
fixed in 8.1.2 

thank you for reporting

**Comment by Ki-Tan2934** [comment]
![image](https://github.com/Darkere/CrashUtilities/assets/58880823/bb39d95c-f698-475d-942b-8d22297a1eca)
You can not select a specific dim still

The other stuff is fixed I can confirm

**Comment by Darkere** [comment]
huh. from what I can tell that has never worked. Should be fixed in 8.1.3 thanks

**Comment by Ki-Tan2934** [comment]
Giving this a bump versus making a new thread. Sorry if not approved :)

Exact same problem in 1.19.2 with not showing find and not being able to find AE2 anything

**Comment by Ki-Tan2934** [comment]
@Darkere Not sure if I can reopen this or if you'll be notified
