### ISSUE TITLE
Crash when trying to view player's inventory

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Darkere/CrashUtilities#4]
When I opened Crash Utilities and tried to view another player's inventory the client crashed. This is obviously on a server.

Minecraft 1.16.3
Forge 34.0.9
crashutilities-3.4
https://paste.ee/p/jFsLN

**Comment by Darkere** [comment]
Thank you for the report. I will look into it.

**Comment by Darkere** [comment]
Should be fixed in 3.5 that I just uploaded. 
Report back if you have any other issues.
