### ISSUE TITLE
[1.21.1-Neo] Crash when teleporting to entity in GUI.

### ISSUE THREAD

**Issue by Gbergz** [Darkere/CrashUtilities#42]
title.

Crash Utilities: 9.0.0
NeoForge: 21.1.49

Crash report: https://gist.githubusercontent.com/Gbergz/3f8102ac39cc01987b2df5fb89b2fd5f/raw/7954b002da91479917b36a7804c2ec7bba54ef77/gistfile1.txt

**Comment by Darkere** [comment]
ty should be fixed in 9.0.1

**Comment by Gbergz** [comment]
Thanks! Confirmed fixed.
