### ISSUE TITLE
Curios API Incompatibility

### ISSUE THREAD

**Issue by NyxaYu** [Darkere/CrashUtilities#43]
We host an ATM10 server and we use Crash Utilities on it, recently after some players have reported their Curios slots being wiped and after some testing it was found to be the Crash Utilities mod itself.

Using the `/cu unstuck` command on an offline player will wipe their Curios slots.
Using the `/cu tp` command will wipe the inventory of either/both player(s) that are offline.

My best guess from looking at the code is that it has something to do with creating a FakePlayer which likely doesn't have any Curios slots and then saving their data that way.

Love from NyxaYu

**Comment by Darkere** [comment]
Which curios mod are you guys using?

**Comment by NyxaYu** [comment]
My apologies,
[Adorned (Curios)](https://www.curseforge.com/minecraft/mc-mods/adorned/) v9.1.4

**Comment by Darkere** [comment]
should be fixed in 9.0.2. Not really a proper fix, but should solve the issue for now
