### ISSUE TITLE
Crash when using the teleport button next to players

### ISSUE THREAD

**Issue by jinkhya** [Darkere/CrashUtilities#5]
Hello, I ran into a crash when using the teleport button next to players in this UI : https://cdn.discordapp.com/attachments/410061831198212108/778368845860700213/unknown.png
(It was an offline player if that matters)

Here's the crashlog : https://gist.github.com/jinkhya/8b06ef23b6287005e44a6da3866ff857

Thanks in advance ! 
Jin

**Comment by Darkere** [comment]
Fixed for next version :) 

Thanks for the report.
