### ISSUE TITLE
[1.15.2] Cannot access GUI even when OP

### ISSUE THREAD

**Issue by DonutInTheRain** [Darkere/CrashUtilities#7]
I receive a prompt that I need to be an OP whenever I try to bring the GUI up even though I am already an OP. I've tried to deop and reop myself, delete the op.json file on the server then recreate it to make a new one.

The mod was added a week after creating the server. I am running the server on the same computer I am playing on as well.

[debug.log](https://github.com/Darkere/CrashUtilities/files/5805704/debug.log)

**Comment by Darkere** [comment]
Currently requires OP permission  level 4. Make zure you have that. 

Will go down to 2 in the next update.

**Comment by DonutInTheRain** [comment]
Oh I see, thank you. My OP permission was set to level 3.
