### ISSUE TITLE
Reduce control setting description lengths

### ISSUE THREAD

**Issue by frank89722** [Darkere/CrashUtilities#9]
After crash utilities installed, the controlling setting menu broken
![image](https://user-images.githubusercontent.com/10683361/106351573-279e9000-6318-11eb-9370-53629354ef0d.png)

This happened on both mc1.16.4 and 1.16.5 with crash utilities-3.8.1 and controlling-7.0.0.12

https://github.com/jaredlll08/Controlling/issues/74

**Comment by nayfaan** [comment]
Can replicate with only crash utilities-3.8.1 installed and nothing else on 1.16.5
<img width="1440" alt="スクリーンショット 2021-02-05 8 49 49" src="https://user-images.githubusercontent.com/10527873/106974385-94d67900-678f-11eb-9774-2877d26f77d0.png">
